require 'erubis'
require 'set'
require 'rake'
require 'rspec'
require 'rspec/core/rake_task'
require 'simplecov'
require_relative 'lib/tic-tac-toe'

RSpec::Core::RakeTask.new(:spec) do |t|
  t.rspec_opts = "--tag ~slow"
end

RSpec::Core::RakeTask.new(:spec_all)

RSpec::Core::RakeTask.new(:spec_coverage) do |t|
  t.rspec_opts = "--tag ~slow"

  SimpleCov.start
end

RSpec::Core::RakeTask.new(:spec_all_coverage) do |t|
  SimpleCov.start
end

desc "Generates piet script"
task :generates_piet_script do
  template = Erubis::Eruby.new(File.read("views/get_computer_move.erb"))

  computer = UnbeatableTicTacToe.new(Game::COMPUTER)
  human    = PlaysAllPossibleMoves.new(Game::HUMAN)

  computer_goes_first = SavesResults.new(computer, human, 1)
  computer_goes_first.play

  human_goes_first = SavesResults.new(human, computer, 2)
  human_goes_first.play

  combined_results = computer_goes_first.results.merge(human_goes_first.results) { |move, computer_boards, human_boards| computer_boards | human_boards }

  File.write("../piet/get_computer_move.script", template.result(binding))
end
